### PR TITLE
fix:variable referenced before assignment

### PR DESCRIPTION
**Pull request by BlancRay**
variable 'uncovered' referenced before assignment if only one superitems_pool

### CODE REVIEW

**Comment by Wadaboa** [comment]
Hi @BlancRay, 

Thank you for your pull request. I was wondering if the correct fix should be `uncovered = 0`, since we'd be covering all items (the only one available) in that case.

Let me know what do you think about it and then I'll merge the change.

Thanks,
Alessio.

**Comment by BlancRay** [comment]
You are right, it should be 0.
But if only one item, 
```python
generated_pools = [layer_pool]
uncovered = [len(pool.not_covered_superitems()) for pool in generated_pools]
# uncovered = [1]
```
then I check the `not_covered_superitems()`, I think it should be
```python
return [s for s in self.superitems_pool if covered_spool.get_index(s) is None]
```
then it makes sense.

**Comment by Wadaboa** [comment]
Hi @BlancRay,

Thank you for your commits. Regarding your change in `not_covered_superitems()`, checking for `False` or checking for `None` should be the same, as `None` evaluates to `False`.

Anyways, I merged your changes. Thanks,
Alessio.

**Comment by BlancRay** [comment]
`get_index` will return index 0, and `0 == False` in python, so you must checking for `None`.

**Comment by Wadaboa** [comment]
You're right, thanks for pointing that out.

**Pull request merged**
